CREATE TABLE "PRO_ATT" (
	"FILE_NO"	NUMBER		NOT NULL,
	"PRO_NO"	NUMBER		NOT NULL,
	"FILE_PATH"	VARCHAR2(1000)		NOT NULL,
	"UPLOAD_DATE"	VARCHAR2(100)	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"FILE_LEVEL"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "PRO_ATT"."FILE_NO" IS '파일번호';

COMMENT ON COLUMN "PRO_ATT"."PRO_NO" IS '상품 번호';

COMMENT ON COLUMN "PRO_ATT"."FILE_PATH" IS '저장폴더경로';

COMMENT ON COLUMN "PRO_ATT"."UPLOAD_DATE" IS '업로드일';

COMMENT ON COLUMN "PRO_ATT"."STATUS" IS 'STATUS';

COMMENT ON COLUMN "PRO_ATT"."FILE_LEVEL" IS 'VARCHAR2(1)';

CREATE TABLE "PRODUCT" (
	"PRO_NO"	NUMBER		NOT NULL,
	"PRO_NAME"	VARCHAR2(500)		NOT NULL,
	"PRICE"	NUMBER		NOT NULL,
	"SOLDOUT"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"EXPIRED_DATE"	VARCHAR2(100)		NOT NULL,
	"ENROLL_DATE"	VARCHAR2(100)	DEFAULT SYSDATE	NOT NULL,
	"SAVE"	NUMBER	DEFAULT 0.1	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"THUMB_IMG"	VARCHAR2(1000)		NOT NULL,
	"CATEGORY"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "PRODUCT"."PRO_NO" IS '상품 번호';

COMMENT ON COLUMN "PRODUCT"."PRO_NAME" IS '상품명';

COMMENT ON COLUMN "PRODUCT"."PRICE" IS '가격';

COMMENT ON COLUMN "PRODUCT"."SOLDOUT" IS '품절여부';

COMMENT ON COLUMN "PRODUCT"."EXPIRED_DATE" IS '유통기한';

COMMENT ON COLUMN "PRODUCT"."ENROLL_DATE" IS '등록일';

COMMENT ON COLUMN "PRODUCT"."SAVE" IS '적립률 (%)';

COMMENT ON COLUMN "PRODUCT"."STATUS" IS 'STATUS';

COMMENT ON COLUMN "PRODUCT"."THUMB_IMG" IS '섬네일경로';

COMMENT ON COLUMN "PRODUCT"."CATEGORY" IS '카테고리';

ALTER TABLE "PRO_ATT" ADD CONSTRAINT "PK_PRO_ATT" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRO_NO"
);

-- 시퀀스 추가

-- 상품 번호 시퀀스
CREATE SEQUENCE SEQ_PRODUCT_NO
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 99999
       NOCYCLE;

--상품 이미지 번호 시퀀스  
CREATE SEQUENCE SEQ_FILE_NO
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 99999
       NOCYCLE;        

       
-- 주문 번호 시퀀스 (아직 사용 안 함)
CREATE SEQUENCE SEQ_ORDER_NO
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 99999
       NOCYCLE;  

       
       
