-- PRODUCT , PRO_ATT
-- TB_ORDER , ORD_PRO, PAYMENT
-- MEMBER , POINT 
-- 테이블 추가


CREATE TABLE "PAYMENT" (
	"PAYMENT_NO"	NUMBER		NOT NULL,
	"ORD_NO"	NUMBER		NOT NULL,
	"DISCOUNT"	NUMBER		NULL,
	"DELIVERY"	NUMBER	DEFAULT 4000	NOT NULL,
	"TOTAL_PRICE"	NUMBER		NOT NULL,
	"PAY_DATE"	DATE		NOT NULL,
	"CARD"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "PAYMENT"."PAYMENT_NO" IS '결제번호';

COMMENT ON COLUMN "PAYMENT"."ORD_NO" IS '주문한 상품가격';

COMMENT ON COLUMN "PAYMENT"."DISCOUNT" IS '적립금할인금액';

COMMENT ON COLUMN "PAYMENT"."DELIVERY" IS '배송비';

COMMENT ON COLUMN "PAYMENT"."TOTAL_PRICE" IS '총가격';

CREATE TABLE "PRO_ATT" (
	"FILE_NO"	NUMBER		NOT NULL,
	"PRO_NO"	NUMBER		NOT NULL,
	"FILE_PATH"	VARCHAR2(1000)		NOT NULL,
	"UPLOAD_DATE"	VARCHAR2(100)	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"FILE_LEVEL"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "PRO_ATT"."FILE_NO" IS '파일번호';

COMMENT ON COLUMN "PRO_ATT"."PRO_NO" IS '상품 번호';

COMMENT ON COLUMN "PRO_ATT"."FILE_PATH" IS '저장폴더경로';

COMMENT ON COLUMN "PRO_ATT"."UPLOAD_DATE" IS '업로드일';

COMMENT ON COLUMN "PRO_ATT"."STATUS" IS 'STATUS';

COMMENT ON COLUMN "PRO_ATT"."FILE_LEVEL" IS 'VARCHAR2(1)';

CREATE TABLE "PRODUCT" (
	"PRO_NO"	NUMBER		NOT NULL,
	"PRO_NAME"	VARCHAR2(500)		NOT NULL,
	"PRICE"	NUMBER		NOT NULL,
	"SOLDOUT"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"EXPIRED_DATE"	VARCHAR2(100)		NOT NULL,
	"ENROLL_DATE"	VARCHAR2(100)	DEFAULT SYSDATE	NOT NULL,
	"SAVE"	NUMBER	DEFAULT 0.1	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"THUMB_IMG"	VARCHAR2(1000)		NOT NULL,
	"CATEGORY"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "PRODUCT"."PRO_NO" IS '상품 번호';

COMMENT ON COLUMN "PRODUCT"."PRO_NAME" IS '상품명';

COMMENT ON COLUMN "PRODUCT"."PRICE" IS '가격';

COMMENT ON COLUMN "PRODUCT"."SOLDOUT" IS '품절여부';

COMMENT ON COLUMN "PRODUCT"."EXPIRED_DATE" IS '유통기한';

COMMENT ON COLUMN "PRODUCT"."ENROLL_DATE" IS '등록일';

COMMENT ON COLUMN "PRODUCT"."SAVE" IS '적립률 (%)';

COMMENT ON COLUMN "PRODUCT"."STATUS" IS 'STATUS';

COMMENT ON COLUMN "PRODUCT"."THUMB_IMG" IS '섬네일경로';

COMMENT ON COLUMN "PRODUCT"."CATEGORY" IS '카테고리';

CREATE TABLE "TB_ORDER" (
	"ORD_NO"	NUMBER		NOT NULL,
	"PRO_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"DEL_ADD"	VARCHAR(30)		NULL,
	"PAYMENT"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"DELIVERY"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"PHONE"	VARCHAR2(100)		NOT NULL,
	"EMAIL"	VARCHAR2(100)		NOT NULL,
	"ADDRESS"	VARCHAR2(100)		NOT NULL,
	"REQUIRE"	VARCHAR2(1000)		NULL
);

COMMENT ON COLUMN "TB_ORDER"."ORD_NO" IS '주문 번호';

COMMENT ON COLUMN "TB_ORDER"."PRO_NO" IS '상품 번호';

COMMENT ON COLUMN "TB_ORDER"."USER_NO" IS '회원 번호';

COMMENT ON COLUMN "TB_ORDER"."DEL_ADD" IS '배송지';

COMMENT ON COLUMN "TB_ORDER"."PAYMENT" IS '입금 여부';

COMMENT ON COLUMN "TB_ORDER"."DELIVERY" IS '배송 시작 여부';

COMMENT ON COLUMN "TB_ORDER"."STATUS" IS 'STATUS';

COMMENT ON COLUMN "TB_ORDER"."PHONE" IS '휴대전화';

COMMENT ON COLUMN "TB_ORDER"."EMAIL" IS '이메일';

COMMENT ON COLUMN "TB_ORDER"."ADDRESS" IS '주소';

COMMENT ON COLUMN "TB_ORDER"."REQUIRE" IS '배송시요청사항';

CREATE TABLE "ORD_PRO" (
	"ORD_NO"	NUMBER		NOT NULL,
	"PRO_NO"	NUMBER		NOT NULL,
	"AMOUNT"	NUMBER	DEFAULT 1	NULL
);

COMMENT ON COLUMN "ORD_PRO"."ORD_NO" IS '주문 번호';

COMMENT ON COLUMN "ORD_PRO"."PRO_NO" IS '상품 번호';

COMMENT ON COLUMN "ORD_PRO"."AMOUNT" IS '수량';

CREATE TABLE "POINT" (
	"POINT_NO"	NUMBER		NOT NULL,
	"POINT_CATEGORY"	VARCHAR2(100)		NOT NULL,
	"POINT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"POINT_USE"	VARCHAR2(1000)		NOT NULL,
	"POINT_PRICE"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"ORD_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "POINT"."POINT_NO" IS '적립금번호';

COMMENT ON COLUMN "POINT"."POINT_CATEGORY" IS '적립/사용';

COMMENT ON COLUMN "POINT"."POINT_DATE" IS '적립및사용날짜';

COMMENT ON COLUMN "POINT"."POINT_USE" IS '적립및사용내역';

COMMENT ON COLUMN "POINT"."POINT_PRICE" IS '적립및사용금액';

COMMENT ON COLUMN "POINT"."USER_NO" IS '회원번호';

COMMENT ON COLUMN "POINT"."ORD_NO" IS '주문 번호';

CREATE TABLE "MEMBER" (
	"USER_NO"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"USER_PWD"	VARCHAR2(20)		NOT NULL,
	"USER_NAME"	VARCHAR2(20)		NOT NULL,
	"EMAIL"	VARCHAR2(30)		NULL,
	"PHONE"	VARCHAR2(20)		NOT NULL,
	"POST_CODE"	NUMBER		NOT NULL,
	"ADDRESS"	VARCHAR2(100)		NOT NULL,
	"DETAILED_ADDRESS"	VARCHAR2(100)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NULL,
	"POINT"	NUMBER	 NULL
);

COMMENT ON COLUMN "MEMBER"."USER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."USER_ID" IS '회원아이디';

COMMENT ON COLUMN "MEMBER"."USER_PWD" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."USER_NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."EMAIL" IS '이메일';

COMMENT ON COLUMN "MEMBER"."PHONE" IS '휴대전화';

COMMENT ON COLUMN "MEMBER"."POST_CODE" IS '주소';

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"PAYMENT_NO"
);

ALTER TABLE "PRO_ATT" ADD CONSTRAINT "PK_PRO_ATT" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRO_NO"
);

ALTER TABLE "TB_ORDER" ADD CONSTRAINT "PK_TB_ORDER" PRIMARY KEY (
	"ORD_NO"
);

ALTER TABLE "POINT" ADD CONSTRAINT "PK_POINT" PRIMARY KEY (
	"POINT_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"USER_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_TB_ORDER_TO_PAYMENT_1" FOREIGN KEY (
	"ORD_NO"
)
REFERENCES "TB_ORDER" (
	"ORD_NO"
);

ALTER TABLE "PRO_ATT" ADD CONSTRAINT "FK_PRODUCT_TO_PRO_ATT_1" FOREIGN KEY (
	"PRO_NO"
)
REFERENCES "PRODUCT" (
	"PRO_NO"
);

ALTER TABLE "TB_ORDER" ADD CONSTRAINT "FK_PRODUCT_TO_TB_ORDER_1" FOREIGN KEY (
	"PRO_NO"
)
REFERENCES "PRODUCT" (
	"PRO_NO"
);

ALTER TABLE "TB_ORDER" ADD CONSTRAINT "FK_MEMBER_TO_TB_ORDER_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "ORD_PRO" ADD CONSTRAINT "FK_TB_ORDER_TO_ORD_PRO_1" FOREIGN KEY (
	"ORD_NO"
)
REFERENCES "TB_ORDER" (
	"ORD_NO"
);

ALTER TABLE "ORD_PRO" ADD CONSTRAINT "FK_PRODUCT_TO_ORD_PRO_1" FOREIGN KEY (
	"PRO_NO"
)
REFERENCES "PRODUCT" (
	"PRO_NO"
);

ALTER TABLE "POINT" ADD CONSTRAINT "FK_MEMBER_TO_POINT_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "POINT" ADD CONSTRAINT "FK_TB_ORDER_TO_POINT_1" FOREIGN KEY (
	"ORD_NO"
)
REFERENCES "TB_ORDER" (
	"ORD_NO"
);

