DROP TABLE "PRODUCT";

CREATE TABLE "PRODUCT" (
	"PRO_NO"	NUMBER		NOT NULL,
	"PRO_NAME"	VARCHAR2(500)		NOT NULL,
	"PRICE"	NUMBER		NOT NULL,
	"SOLDOUT"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"EXPIRED_DATE"	VARCHAR2(100)		NOT NULL,
	"ENROLL_DATE"	VARCHAR2(100)	DEFAULT SYSDATE	NOT NULL,
	"SAVE"	NUMBER	DEFAULT 0.1	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"THUMB_IMG"	VARCHAR2(1000)		NOT NULL,
	"CATEGORY"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "PRODUCT"."PRO_NO" IS '상품 번호';

COMMENT ON COLUMN "PRODUCT"."PRO_NAME" IS '상품명';

COMMENT ON COLUMN "PRODUCT"."PRICE" IS '가격';

COMMENT ON COLUMN "PRODUCT"."SOLDOUT" IS '품절여부';

COMMENT ON COLUMN "PRODUCT"."EXPIRED_DATE" IS '유통기한';

COMMENT ON COLUMN "PRODUCT"."ENROLL_DATE" IS '등록일';

COMMENT ON COLUMN "PRODUCT"."SAVE" IS '적립률 (%)';

COMMENT ON COLUMN "PRODUCT"."STATUS" IS 'STATUS';

COMMENT ON COLUMN "PRODUCT"."THUMB_IMG" IS '섬네일경로';

COMMENT ON COLUMN "PRODUCT"."CATEGORY" IS '카테고리';

DROP TABLE "ORD_PRO";

CREATE TABLE "ORD_PRO" (
	"ORD_NO"	NUMBER		NOT NULL,
	"PRO_NO"	NUMBER		NOT NULL,
	"AMOUNT"	NUMBER	DEFAULT 1	NULL
);

COMMENT ON COLUMN "ORD_PRO"."ORD_NO" IS '주문 번호';

COMMENT ON COLUMN "ORD_PRO"."PRO_NO" IS '상품 번호';

COMMENT ON COLUMN "ORD_PRO"."AMOUNT" IS '수량';

DROP TABLE "PRO_ATT";

CREATE TABLE "PRO_ATT" (
	"FILE_NO"	NUMBER		NOT NULL,
	"PRO_NO"	NUMBER		NOT NULL,
	"FILE_PATH"	VARCHAR2(1000)		NOT NULL,
	"UPLOAD_DATE"	VARCHAR2(100)	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"FILE_LEVEL"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "PRO_ATT"."FILE_NO" IS '파일번호';

COMMENT ON COLUMN "PRO_ATT"."PRO_NO" IS '상품 번호';

COMMENT ON COLUMN "PRO_ATT"."FILE_PATH" IS '저장폴더경로';

COMMENT ON COLUMN "PRO_ATT"."UPLOAD_DATE" IS '업로드일';

COMMENT ON COLUMN "PRO_ATT"."STATUS" IS 'STATUS';

COMMENT ON COLUMN "PRO_ATT"."FILE_LEVEL" IS 'VARCHAR2(1)';

DROP TABLE "PAYMENT";

CREATE TABLE "PAYMENT" (
	"PAYMENT_NO"	NUMBER		NOT NULL,
	"ORD_NO"	NUMBER		NOT NULL,
	"Field"	VARCHAR(255)		NULL,
	"DISCOUNT"	NUMBER		NULL,
	"DELIVERY"	NUMBER	DEFAULT 4000	NOT NULL,
	"TOTAL_PRICE"	NUMBER		NOT NULL,
	"Field2"	DATE		NOT NULL,
	"Field3"	VARCHAR2(50)		NULL
);

COMMENT ON COLUMN "PAYMENT"."PAYMENT_NO" IS '결제번호';

COMMENT ON COLUMN "PAYMENT"."ORD_NO" IS '주문 번호';

COMMENT ON COLUMN "PAYMENT"."DISCOUNT" IS '적립금할인금액';

COMMENT ON COLUMN "PAYMENT"."DELIVERY" IS '배송비';

COMMENT ON COLUMN "PAYMENT"."TOTAL_PRICE" IS '총가격';

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRO_NO"
);

ALTER TABLE "PRO_ATT" ADD CONSTRAINT "PK_PRO_ATT" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"PAYMENT_NO"
);

ALTER TABLE "ORD_PRO" ADD CONSTRAINT "FK_ORDER_TO_ORD_PRO_1" FOREIGN KEY (
	"ORD_NO"
)
REFERENCES "ORDER" (
	"ORD_NO"
);

ALTER TABLE "ORD_PRO" ADD CONSTRAINT "FK_PRODUCT_TO_ORD_PRO_1" FOREIGN KEY (
	"PRO_NO"
)
REFERENCES "PRODUCT" (
	"PRO_NO"
);

ALTER TABLE "PRO_ATT" ADD CONSTRAINT "FK_PRODUCT_TO_PRO_ATT_1" FOREIGN KEY (
	"PRO_NO"
)
REFERENCES "PRODUCT" (
	"PRO_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_ORDER_TO_PAYMENT_1" FOREIGN KEY (
	"ORD_NO"
)
REFERENCES "ORDER" (
	"ORD_NO"
);

