--------------------------------------------------------
--  파일이 생성됨 - 일요일-2월-05-2023   
--------------------------------------------------------
REM INSERTING into ODODOG.TB_ORDER
REM INSERTING into ODODOG.PAYMENT
SET DEFINE OFF;

Insert into ODODOG.TB_ORDER (ORD_NO,USER_NO,DEL_ADD,PAYMENT,DELIVERY,STATUS,PHONE,EMAIL,ADDRESS,REQUIRE,ORDER_DATE) values (SEQ_ORDERNO.NEXTVAL,4,'배송지1','Y','N','Y','핸드폰1','이메일1','주소1','요구사항1',to_date('23/02/05','RR/MM/DD'));

Insert into ODODOG.ORD_PRO (ORD_PRO_NO,ORD_NO,PRO_NO,AMOUNT) values (SEQ_ORDPRONO.NEXTVAL,SEQ_ORDERNO.CURRVAL,5,2);
Insert into ODODOG.ORD_PRO (ORD_PRO_NO,ORD_NO,PRO_NO,AMOUNT) values (SEQ_ORDPRONO.NEXTVAL,SEQ_ORDERNO.CURRVAL,4,1);


Insert into ODODOG.PAYMENT (PAYMENT_NO,ORD_NO,DISCOUNT,DELIVERY,TOTAL_PRICE,PAY_DATE,CARD) values (SEQ_PAYMENT.NEXTVAL,SEQ_ORDERNO.CURRVAL,1000,4000,91000,to_date('23/02/05','RR/MM/DD'),'신한');

---

Insert into ODODOG.TB_ORDER (ORD_NO,USER_NO,DEL_ADD,PAYMENT,DELIVERY,STATUS,PHONE,EMAIL,ADDRESS,REQUIRE,ORDER_DATE) values (SEQ_ORDERNO.NEXTVAL,9,'배송지2','Y','N','Y','핸드폰2','이메일2','주소2','요구사항2',to_date('23/02/05','RR/MM/DD'));

Insert into ODODOG.ORD_PRO (ORD_PRO_NO,ORD_NO,PRO_NO,AMOUNT) values (SEQ_ORDPRONO.NEXTVAL,SEQ_ORDERNO.CURRVAL,9,4);
Insert into ODODOG.ORD_PRO (ORD_PRO_NO,ORD_NO,PRO_NO,AMOUNT) values (SEQ_ORDPRONO.NEXTVAL,SEQ_ORDERNO.CURRVAL,1,5);

Insert into ODODOG.PAYMENT (PAYMENT_NO,ORD_NO,DISCOUNT,DELIVERY,TOTAL_PRICE,PAY_DATE,CARD) values (SEQ_PAYMENT.NEXTVAL,SEQ_ORDERNO.CURRVAL,null,2000,92000,to_date('23/02/05','RR/MM/DD'),'신한');

---

Insert into ODODOG.TB_ORDER (ORD_NO,USER_NO,DEL_ADD,PAYMENT,DELIVERY,STATUS,PHONE,EMAIL,ADDRESS,REQUIRE,ORDER_DATE) values (SEQ_ORDERNO.NEXTVAL,1,'배송지3','Y','N','Y','핸드폰3','이메일3','주소3','요구사항3',to_date('23/02/05','RR/MM/DD'));

Insert into ODODOG.ORD_PRO (ORD_PRO_NO,ORD_NO,PRO_NO,AMOUNT) values (SEQ_ORDPRONO.NEXTVAL,SEQ_ORDERNO.CURRVAL,12,1);
Insert into ODODOG.ORD_PRO (ORD_PRO_NO,ORD_NO,PRO_NO,AMOUNT) values (SEQ_ORDPRONO.NEXTVAL,SEQ_ORDERNO.CURRVAL,5,2);
Insert into ODODOG.ORD_PRO (ORD_PRO_NO,ORD_NO,PRO_NO,AMOUNT) values (SEQ_ORDPRONO.NEXTVAL,SEQ_ORDERNO.CURRVAL,7,1);

Insert into ODODOG.PAYMENT (PAYMENT_NO,ORD_NO,DISCOUNT,DELIVERY,TOTAL_PRICE,PAY_DATE,CARD) values (SEQ_PAYMENT.NEXTVAL,SEQ_ORDERNO.CURRVAL,2000,4000,118000,to_date('23/02/05','RR/MM/DD'),'국민');

---

Insert into ODODOG.TB_ORDER (ORD_NO,USER_NO,DEL_ADD,PAYMENT,DELIVERY,STATUS,PHONE,EMAIL,ADDRESS,REQUIRE,ORDER_DATE) values (SEQ_ORDERNO.NEXTVAL,4,'배송지4','Y','N','Y','핸드폰4','이메일4','주소4','요구사항4',to_date('23/02/05','RR/MM/DD'));

Insert into ODODOG.ORD_PRO (ORD_PRO_NO,ORD_NO,PRO_NO,AMOUNT) values (SEQ_ORDPRONO.NEXTVAL,SEQ_ORDERNO.CURRVAL,2,3);

Insert into ODODOG.PAYMENT (PAYMENT_NO,ORD_NO,DISCOUNT,DELIVERY,TOTAL_PRICE,PAY_DATE,CARD) values (SEQ_PAYMENT.NEXTVAL,SEQ_ORDERNO.CURRVAL,4000,3000,80000,to_date('23/02/05','RR/MM/DD'),'국민');

---

Insert into ODODOG.TB_ORDER (ORD_NO,USER_NO,DEL_ADD,PAYMENT,DELIVERY,STATUS,PHONE,EMAIL,ADDRESS,REQUIRE,ORDER_DATE) values (SEQ_ORDERNO.NEXTVAL,7,'배송지5','Y','N','Y','핸드폰5','이메일5','주소5','요구사항5',to_date('23/02/05','RR/MM/DD'));

Insert into ODODOG.ORD_PRO (ORD_PRO_NO,ORD_NO,PRO_NO,AMOUNT) values (SEQ_ORDPRONO.NEXTVAL,SEQ_ORDERNO.CURRVAL,8,2);
Insert into ODODOG.ORD_PRO (ORD_PRO_NO,ORD_NO,PRO_NO,AMOUNT) values (SEQ_ORDPRONO.NEXTVAL,SEQ_ORDERNO.CURRVAL,4,3);
Insert into ODODOG.ORD_PRO (ORD_PRO_NO,ORD_NO,PRO_NO,AMOUNT) values (SEQ_ORDPRONO.NEXTVAL,SEQ_ORDERNO.CURRVAL,10,1);

Insert into ODODOG.PAYMENT (PAYMENT_NO,ORD_NO,DISCOUNT,DELIVERY,TOTAL_PRICE,PAY_DATE,CARD) values (SEQ_PAYMENT.NEXTVAL,SEQ_ORDERNO.CURRVAL,null,4000,151000,to_date('23/02/05','RR/MM/DD'),'신한');


---

Insert into ODODOG.TB_ORDER (ORD_NO,USER_NO,DEL_ADD,PAYMENT,DELIVERY,STATUS,PHONE,EMAIL,ADDRESS,REQUIRE,ORDER_DATE) values (SEQ_ORDERNO.NEXTVAL,6,'배송지6','Y','N','Y','핸드폰6','이메일6','주소6','요구사항6',to_date('23/02/05','RR/MM/DD'));

Insert into ODODOG.ORD_PRO (ORD_PRO_NO,ORD_NO,PRO_NO,AMOUNT) values (SEQ_ORDPRONO.NEXTVAL,SEQ_ORDERNO.CURRVAL,13,3);
Insert into ODODOG.ORD_PRO (ORD_PRO_NO,ORD_NO,PRO_NO,AMOUNT) values (SEQ_ORDPRONO.NEXTVAL,SEQ_ORDERNO.CURRVAL,4,1);

Insert into ODODOG.PAYMENT (PAYMENT_NO,ORD_NO,DISCOUNT,DELIVERY,TOTAL_PRICE,PAY_DATE,CARD) values (SEQ_PAYMENT.NEXTVAL,SEQ_ORDERNO.CURRVAL,2000,2000,116000,to_date('23/02/05','RR/MM/DD'),'국민');
COMMIT;



