-- 추가 변경 사항

DROP SEQUENCE SEQ_CONSULT;
DROP SEQUENCE  SEQ_PAYMENT;
DROP SEQUENCE  SEQ_REVIEW;

CREATE SEQUENCE SEQ_CONSULTNO
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 99999
       NOCYCLE; 
       
CREATE SEQUENCE SEQ_PAYMENTYNO
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 99999
       NOCYCLE; 
       
CREATE SEQUENCE SEQ_REVIEWNO
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 99999
       NOCYCLE; 

COMMENT ON COLUMN POINT.POINT_CATEGORY IS '적립1/사용2';

ALTER TABLE FAQ MODIFY(CONTACT_TITLE VARCHAR2(100BYTE));
