--행 1
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,1,'공지사항입니다!','나는 내용입니다1',1,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 2
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목2','나는 내용입니다2',2,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 3
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목3','나는 내용입니다3',3,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 4
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목4','나는 내용입니다4',4,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 5
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목5','나는 내용입니다5',5,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 6
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목6','나는 내용입니다6',2,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 7
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목7','나는 내용입니다7',3,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 8
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목8','나는 내용입니다8',4,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 9
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목9','나는 내용입니다9',5,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 10
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목10','나는 내용입니다10',2,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 11
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목11','나는 내용입니다11',3,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 12
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목12','나는 내용입니다12',4,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 13
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목13','나는 내용입니다13',5,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 14
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목14','나는 내용입니다14',2,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 15
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목15','나는 내용입니다15',3,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 16
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목16','나는 내용입니다16',4,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 17
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목17','나는 내용입니다17',5,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 18
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목18','나는 내용입니다18',2,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 19
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목19','나는 내용입니다19',3,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 20
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목20','나는 내용입니다20',4,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 21
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목21','나는 내용입니다21',5,0,to_date('2023-01-01', 'RRRR-MM-DD'),'Y');
--행 22
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목22','나는 내용입니다22',2,0,to_date('2023-01-02', 'RRRR-MM-DD'),'Y');
--행 23
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목23','나는 내용입니다23',3,0,to_date('2023-01-03', 'RRRR-MM-DD'),'Y');
--행 24
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목24','나는 내용입니다24',4,0,to_date('2023-01-04', 'RRRR-MM-DD'),'Y');
--행 25
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목25','나는 내용입니다25',5,0,to_date('2023-01-05', 'RRRR-MM-DD'),'Y');
--행 26
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목26','나는 내용입니다26',2,0,to_date('2023-01-06', 'RRRR-MM-DD'),'Y');
--행 27
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목27','나는 내용입니다27',3,0,to_date('2023-01-07', 'RRRR-MM-DD'),'Y');
--행 28
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목28','나는 내용입니다28',4,0,to_date('2023-01-08', 'RRRR-MM-DD'),'Y');
--행 29
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목29','나는 내용입니다29',5,0,to_date('2023-01-09', 'RRRR-MM-DD'),'Y');
--행 30
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목30','나는 내용입니다30',2,0,to_date('2023-01-10', 'RRRR-MM-DD'),'Y');
--행 31
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목31','나는 내용입니다31',3,0,to_date('2023-01-11', 'RRRR-MM-DD'),'Y');
--행 32
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목32','나는 내용입니다32',4,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 33
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목33','나는 내용입니다33',5,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 34
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목34','나는 내용입니다34',2,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 35
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목35','나는 내용입니다35',3,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 36
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목36','나는 내용입니다36',4,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 37
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목37','나는 내용입니다37',5,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 38
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목38','나는 내용입니다38',2,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 39
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목39','나는 내용입니다39',3,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 40
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목40','나는 내용입니다40',4,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 41
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목41','나는 내용입니다41',5,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 42
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목42','나는 내용입니다42',2,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 43
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목43','나는 내용입니다43',3,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 44
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목44','나는 내용입니다44',4,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 45
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목45','나는 내용입니다45',5,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 46
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목46','나는 내용입니다46',2,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 47
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목47','나는 내용입니다47',3,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 48
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목48','나는 내용입니다48',4,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 49
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목49','나는 내용입니다49',5,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 50
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목50','나는 내용입니다50',2,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 51
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목51','나는 내용입니다51',3,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 52
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목52','나는 내용입니다52',4,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 53
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목53','나는 내용입니다53',5,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 54
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목54','나는 내용입니다54',2,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 55
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목55','나는 내용입니다55',3,0,to_date('2023-01-12', 'RRRR-MM-DD'),'Y');
--행 56
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목56','나는 내용입니다56',4,0,to_date('2023-01-13', 'RRRR-MM-DD'),'Y');
--행 57
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목57','나는 내용입니다57',5,0,to_date('2023-01-14', 'RRRR-MM-DD'),'Y');
--행 58
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목58','나는 내용입니다58',2,0,to_date('2023-01-15', 'RRRR-MM-DD'),'Y');
--행 59
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목59','나는 내용입니다59',3,0,to_date('2023-01-16', 'RRRR-MM-DD'),'Y');
--행 60
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목60','나는 내용입니다60',4,0,to_date('2023-01-17', 'RRRR-MM-DD'),'Y');
--행 61
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목61','나는 내용입니다61',5,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 62
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목62','나는 내용입니다62',2,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 63
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목63','나는 내용입니다63',3,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 64
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목64','나는 내용입니다64',4,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 65
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목65','나는 내용입니다65',5,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 66
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목66','나는 내용입니다66',2,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 67
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목67','나는 내용입니다67',3,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 68
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목68','나는 내용입니다68',4,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 69
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목69','나는 내용입니다69',5,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 70
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목70','나는 내용입니다70',2,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 71
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목71','나는 내용입니다71',3,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 72
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목72','나는 내용입니다72',4,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 73
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목73','나는 내용입니다73',5,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 74
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목74','나는 내용입니다74',2,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 75
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목75','나는 내용입니다75',3,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 76
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목76','나는 내용입니다76',4,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 77
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,1,'안녕하세요 공지입니다','나는 내용입니다77',1,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 78
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,1,'또 공지여요','나는 내용입니다78',1,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 79
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,1,'주목','나는 내용입니다79',1,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 80
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목80','나는 내용입니다80',2,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 81
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목81','나는 내용입니다81',3,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 82
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목82','나는 내용입니다82',4,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 83
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목83','나는 내용입니다83',5,0,to_date('2023-01-18', 'RRRR-MM-DD'),'Y');
--행 84
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목84','나는 내용입니다84',2,0,to_date('2023-01-19', 'RRRR-MM-DD'),'Y');
--행 85
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목85','나는 내용입니다85',3,0,to_date('2023-01-20', 'RRRR-MM-DD'),'Y');
--행 86
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목86','나는 내용입니다86',4,0,to_date('2023-01-21', 'RRRR-MM-DD'),'Y');
--행 87
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목87','나는 내용입니다87',5,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 88
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목88','나는 내용입니다88',2,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 89
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목89','나는 내용입니다89',3,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 90
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목90','나는 내용입니다90',4,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 91
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목91','나는 내용입니다91',5,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 92
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목92','나는 내용입니다92',2,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 93
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목93','나는 내용입니다93',3,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 94
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목94','나는 내용입니다94',4,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 95
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목95','나는 내용입니다95',5,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 96
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목96','나는 내용입니다96',2,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 97
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목97','나는 내용입니다97',3,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 98
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목98','나는 내용입니다98',4,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 99
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목99','나는 내용입니다99',5,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 100
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목100','나는 내용입니다100',2,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 101
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목101','나는 내용입니다101',3,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 102
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목102','나는 내용입니다102',4,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 103
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목103','나는 내용입니다103',5,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 104
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목104','나는 내용입니다104',2,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 105
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목105','나는 내용입니다105',3,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 106
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목106','나는 내용입니다106',4,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 107
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목107','나는 내용입니다107',5,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 108
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목108','나는 내용입니다108',2,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 109
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목109','나는 내용입니다109',3,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 110
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목110','나는 내용입니다110',4,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 111
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목111','나는 내용입니다111',5,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 112
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목112','나는 내용입니다112',2,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 113
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목113','나는 내용입니다113',3,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 114
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목114','나는 내용입니다114',4,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 115
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목115','나는 내용입니다115',5,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 116
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목116','나는 내용입니다116',2,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 117
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목117','나는 내용입니다117',3,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 118
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목118','나는 내용입니다118',4,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 119
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목119','나는 내용입니다119',5,0,to_date('2023-01-22', 'RRRR-MM-DD'),'Y');
--행 120
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목120','나는 내용입니다120',2,0,to_date('2023-01-23', 'RRRR-MM-DD'),'Y');
--행 121
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목121','나는 내용입니다121',3,0,to_date('2023-01-24', 'RRRR-MM-DD'),'Y');
--행 122
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목122','나는 내용입니다122',4,0,to_date('2023-01-25', 'RRRR-MM-DD'),'Y');
--행 123
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목123','나는 내용입니다123',5,0,to_date('2023-01-25', 'RRRR-MM-DD'),'Y');
--행 124
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목124','나는 내용입니다124',2,0,to_date('2023-01-25', 'RRRR-MM-DD'),'Y');
--행 125
INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS) VALUES (SEQ_BOARDNO.NEXTVAL,2,'나는 제목125','나는 내용입니다125',3,0,to_date('2023-01-25', 'RRRR-MM-DD'),'Y');
COMMIT;