--------------------------------------------------------
--  파일이 생성됨 - 월요일-2월-06-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "ODODOG"."BOARD" 
   (	"BOARD_NO" NUMBER, 
	"BOARD_TYPE" NUMBER, 
	"BOARD_TITLE" VARCHAR2(100 BYTE), 
	"BOARD_CONTENT" CLOB, 
	"BOARD_WRITER" NUMBER, 
	"COUNT" NUMBER DEFAULT 0, 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("BOARD_CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "ODODOG"."BOARD"."BOARD_NO" IS '게시글번호';
   COMMENT ON COLUMN "ODODOG"."BOARD"."BOARD_TYPE" IS '공지사항(1) / 자유게시판(2)';
   COMMENT ON COLUMN "ODODOG"."BOARD"."BOARD_TITLE" IS '게시글제목';
   COMMENT ON COLUMN "ODODOG"."BOARD"."BOARD_CONTENT" IS '게시글내용';
   COMMENT ON COLUMN "ODODOG"."BOARD"."BOARD_WRITER" IS '회원번호 / 관리자번호';
   COMMENT ON COLUMN "ODODOG"."BOARD"."COUNT" IS '조회수';
   COMMENT ON COLUMN "ODODOG"."BOARD"."CREATE_DATE" IS '게시글작성일';
   COMMENT ON COLUMN "ODODOG"."BOARD"."STATUS" IS '상태';
REM INSERTING into ODODOG.BOARD
SET DEFINE OFF;
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (1,1,'공지사항입니다',1,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (2,2,'나는 제목2',2,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (3,2,'나는 제목3',3,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (4,2,'나는 제목4',2,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (5,2,'나는 제목5',3,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (6,2,'나는 제목6',2,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (7,2,'나는 제목7',3,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (8,2,'나는 제목8',2,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (9,2,'나는 제목9',3,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (10,2,'나는 제목10',2,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (11,2,'나는 제목11',3,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (12,2,'나는 제목12',2,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (13,2,'나는 제목13',3,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (14,2,'나는 제목14',2,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (15,2,'나는 제목15',3,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (16,2,'나는 제목16',2,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (17,2,'나는 제목17',3,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (18,2,'나는 제목18',2,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (19,2,'나는 제목19',3,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (20,2,'나는 제목20',2,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (21,2,'나는 제목21',3,0,to_date('23/01/01','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (22,2,'나는 제목22',2,0,to_date('23/01/02','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (23,2,'나는 제목23',3,0,to_date('23/01/03','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (24,2,'나는 제목24',2,0,to_date('23/01/04','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (25,2,'나는 제목25',3,0,to_date('23/01/05','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (26,2,'나는 제목26',2,0,to_date('23/01/06','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (27,2,'나는 제목27',3,0,to_date('23/01/07','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (28,2,'나는 제목28',2,0,to_date('23/01/08','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (29,2,'나는 제목29',3,0,to_date('23/01/09','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (30,2,'나는 제목30',2,0,to_date('23/01/10','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (31,2,'나는 제목31',3,0,to_date('23/01/11','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (32,2,'나는 제목32',2,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (33,2,'나는 제목33',3,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (34,2,'나는 제목34',2,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (35,2,'나는 제목35',3,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (36,2,'나는 제목36',2,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (37,2,'나는 제목37',3,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (38,2,'나는 제목38',2,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (39,2,'나는 제목39',3,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (40,2,'나는 제목40',2,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (41,2,'나는 제목41',3,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (42,2,'나는 제목42',2,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (43,2,'나는 제목43',3,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (44,2,'나는 제목44',2,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (45,2,'나는 제목45',3,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (46,2,'나는 제목46',2,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (47,2,'나는 제목47',3,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (48,2,'나는 제목48',2,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (49,2,'나는 제목49',3,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (50,2,'나는 제목50',2,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (51,2,'나는 제목51',3,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (52,2,'나는 제목52',2,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (53,2,'나는 제목53',3,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (54,2,'나는 제목54',2,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (55,2,'나는 제목55',3,0,to_date('23/01/12','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (56,2,'나는 제목56',2,0,to_date('23/01/13','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (57,2,'나는 제목57',3,0,to_date('23/01/14','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (58,2,'나는 제목58',2,0,to_date('23/01/15','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (59,2,'나는 제목59',3,0,to_date('23/01/16','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (60,2,'나는 제목60',2,0,to_date('23/01/17','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (61,2,'나는 제목61',3,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (62,2,'나는 제목62',2,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (63,2,'나는 제목63',3,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (64,2,'나는 제목64',2,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (65,2,'나는 제목65',3,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (66,2,'나는 제목66',2,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (67,2,'나는 제목67',3,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (68,2,'나는 제목68',2,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (69,2,'나는 제목69',3,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (70,2,'나는 제목70',2,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (71,2,'나는 제목71',3,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (72,2,'나는 제목72',2,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (73,2,'나는 제목73',3,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (74,2,'나는 제목74',2,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (75,2,'나는 제목75',3,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (76,2,'나는 제목76',2,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (77,1,'공지사항 후후',1,1,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (78,1,'이것도 공지사항',1,1,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (79,1,'이것도 공지사항이어요',1,7,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (80,2,'나는 제목80',2,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (81,2,'나는 제목81',3,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (82,2,'나는 제목82',2,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (83,2,'나는 제목83',3,0,to_date('23/01/18','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (84,2,'나는 제목84',2,0,to_date('23/01/19','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (85,2,'나는 제목85',3,0,to_date('23/01/20','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (86,2,'나는 제목86',2,0,to_date('23/01/21','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (87,2,'나는 제목87',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (88,2,'나는 제목88',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (89,2,'나는 제목89',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (90,2,'나는 제목90',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (91,2,'나는 제목91',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (92,2,'나는 제목92',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (93,2,'나는 제목93',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (94,2,'나는 제목94',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (95,2,'나는 제목95',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (96,2,'나는 제목96',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (97,2,'나는 제목97',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (98,2,'나는 제목98',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (99,2,'나는 제목99',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (100,2,'나는 제목100',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (101,2,'나는 제목101',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (102,2,'나는 제목102',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (103,2,'나는 제목103',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (104,2,'나는 제목104',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (105,2,'나는 제목105',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (106,2,'나는 제목106',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (107,2,'나는 제목107',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (108,2,'나는 제목108',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (109,2,'나는 제목109',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (110,2,'나는 제목110',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (111,2,'나는 제목111',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (112,2,'나는 제목112',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (113,2,'나는 제목113',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (114,2,'나는 제목114',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (115,2,'나는 제목115',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (116,2,'나는 제목116',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (117,2,'나는 제목117',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (118,2,'나는 제목118',2,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (119,2,'나는 제목119',3,0,to_date('23/01/22','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (120,2,'나는 제목120',2,1,to_date('23/01/23','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (121,2,'나는 제목121',3,0,to_date('23/01/24','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (122,2,'나는 제목122',2,0,to_date('23/01/25','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (123,2,'나는 제목123',3,0,to_date('23/01/25','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (124,2,'나는 제목124',2,3,to_date('23/01/25','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (125,2,'나는 제목125',3,6,to_date('23/01/25','RR/MM/DD'),'Y');
Insert into ODODOG.BOARD (BOARD_NO,BOARD_TYPE,BOARD_TITLE,BOARD_WRITER,COUNT,CREATE_DATE,STATUS) values (126,2,'안녕하세요',1,1,to_date('23/02/05','RR/MM/DD'),'N');
--------------------------------------------------------
--  DDL for Index PK_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODODOG"."PK_BOARD" ON "ODODOG"."BOARD" ("BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "ODODOG"."BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY ("BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ODODOG"."BOARD" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."BOARD" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."BOARD" MODIFY ("COUNT" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."BOARD" MODIFY ("BOARD_WRITER" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."BOARD" MODIFY ("BOARD_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."BOARD" MODIFY ("BOARD_TITLE" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."BOARD" MODIFY ("BOARD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."BOARD" MODIFY ("BOARD_NO" NOT NULL ENABLE);
