--------------------------------------------------------
--  파일이 생성됨 - 월요일-2월-06-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RECIPE
--------------------------------------------------------

  CREATE TABLE "ODODOG"."RECIPE" 
   (	"RECIPE_NO" NUMBER, 
	"RECIPE_TITLE" VARCHAR2(100 BYTE), 
	"RECIPE_CONTENT" VARCHAR2(1000 BYTE), 
	"THUMBIMG" VARCHAR2(1000 BYTE), 
	"EFFECT" VARCHAR2(50 BYTE), 
	"TIME" NUMBER, 
	"INGREDIENT" VARCHAR2(1000 BYTE), 
	"PROCESS_COUNT" NUMBER DEFAULT 2, 
	"COUNT" NUMBER DEFAULT 0, 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ODODOG"."RECIPE"."RECIPE_NO" IS '레시피글번호';
   COMMENT ON COLUMN "ODODOG"."RECIPE"."RECIPE_TITLE" IS '레시피제목';
   COMMENT ON COLUMN "ODODOG"."RECIPE"."RECIPE_CONTENT" IS '레시피소개';
   COMMENT ON COLUMN "ODODOG"."RECIPE"."THUMBIMG" IS '썸네일파일경로+수정명';
   COMMENT ON COLUMN "ODODOG"."RECIPE"."EFFECT" IS '효과(10,20,30,40,50)';
   COMMENT ON COLUMN "ODODOG"."RECIPE"."TIME" IS '소요시간(10, 20, 30, 40)';
   COMMENT ON COLUMN "ODODOG"."RECIPE"."INGREDIENT" IS '재료들';
   COMMENT ON COLUMN "ODODOG"."RECIPE"."PROCESS_COUNT" IS '요리순서개수(2~10)';
   COMMENT ON COLUMN "ODODOG"."RECIPE"."COUNT" IS '조회수';
   COMMENT ON COLUMN "ODODOG"."RECIPE"."CREATE_DATE" IS '레시피글작성일';
   COMMENT ON COLUMN "ODODOG"."RECIPE"."STATUS" IS '상태';
REM INSERTING into ODODOG.RECIPE
SET DEFINE OFF;
Insert into ODODOG.RECIPE (RECIPE_NO,RECIPE_TITLE,RECIPE_CONTENT,THUMBIMG,EFFECT,TIME,INGREDIENT,PROCESS_COUNT,COUNT,CREATE_DATE,STATUS) values (1,'소간칩 칙촉','소간으로 모양을 낸 강아지 전용 쿠키','resources/recipe_img/2023020221282855557.png','20',20,'고구마,쌀가루,캐롭분말,올리브유,꿀,소간칩 (기성품 사용 가능)',4,3,to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.RECIPE (RECIPE_NO,RECIPE_TITLE,RECIPE_CONTENT,THUMBIMG,EFFECT,TIME,INGREDIENT,PROCESS_COUNT,COUNT,CREATE_DATE,STATUS) values (2,'소간칩 칙촉','소간칩으로 모양을 낸 강아지 전용 쿠키','resources/recipe_img/2023020221411929265.png','20',20,'고구마,쌀가루,캐롭분말,올리브유,꿀,소간칩',4,16,to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.RECIPE (RECIPE_NO,RECIPE_TITLE,RECIPE_CONTENT,THUMBIMG,EFFECT,TIME,INGREDIENT,PROCESS_COUNT,COUNT,CREATE_DATE,STATUS) values (3,'캐롭 짜장면','댕댕이 전용 짜장면 만들기!','resources/recipe_img/2023020221452279306.png','20',null,'호박,당근,새송이버섯,돼지고기,캐롭가루,면두부',6,4,to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.RECIPE (RECIPE_NO,RECIPE_TITLE,RECIPE_CONTENT,THUMBIMG,EFFECT,TIME,INGREDIENT,PROCESS_COUNT,COUNT,CREATE_DATE,STATUS) values (4,'땅콩버터와 코코넛 머핀','코코넛은 좋은 포화지방이 많고 건조하고 가려운 피부, 알레르기, 소화, 영양소 흡수, 체중감소 등에 도움을 줍니다. 땅콩버터와 섞이면, 이 달콤한 음식이 강아지에게 또 다른 인기 있는 음식이 될 것입니다.','resources/recipe_img/2023020221490065089.jfif','10,20',20,'불린 현미밥,콘플레이크,땅콩버터,코코넛가루,달걀',6,5,to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.RECIPE (RECIPE_NO,RECIPE_TITLE,RECIPE_CONTENT,THUMBIMG,EFFECT,TIME,INGREDIENT,PROCESS_COUNT,COUNT,CREATE_DATE,STATUS) values (7,'오트밀 쿠키','오트밀은 GI지수가 낮고 강아지를 위한 수용성 단백질과 섬유질의 훌륭한 공급원입니다! 오트밀로 만들어보는 맛있는 머핀!','resources/recipe_img/2023020222072320760.jpeg','10,20,50',20,'통밀가루,오트밀가루,무지방우유,꿀,달걀,식물성오일,베이킹파우더,베이킹소다,계피',7,3,to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.RECIPE (RECIPE_NO,RECIPE_TITLE,RECIPE_CONTENT,THUMBIMG,EFFECT,TIME,INGREDIENT,PROCESS_COUNT,COUNT,CREATE_DATE,STATUS) values (8,'바나나 오트밀 쿠키','바나나 오트밀 쿠키는 신선한 과일과 채소로 만든 강아지를 위한 훌륭한 간식입니다. 주재료는 바나나입니다! 우리처럼 강아지들도 달콤한 바나나를 좋아합니다. 바나나는 당류가 많고 탄수화물의 함량이 높지만, 비타민의 훌륭한 공급원이며 칼륨, 마그네슘, 비타민C, 식이성 섬유 등의 무기질을 제공합니다. 바나나는 1년 내내 먹을 수 있고 가격도 비교적 저렴한 과일이며 강아지 간식으로 만들기 좋은 훌륭한 재료입니다.','resources/recipe_img/2023020222130916052.jpeg','20',20,'으깬귀리,바나나,밀가루,호두,사과소스,꿀,식물성오일,계피,베이킹소다',6,3,to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.RECIPE (RECIPE_NO,RECIPE_TITLE,RECIPE_CONTENT,THUMBIMG,EFFECT,TIME,INGREDIENT,PROCESS_COUNT,COUNT,CREATE_DATE,STATUS) values (9,'고구마 튀김','고구마에는 클로로겐산, 비타민C, 베타카로틴, 안토시아닌 등 항산화 성분이 풍부합니다. 꾸준하게 섭취할 경우 활성산소로 인한 여러 질병과 세포와 산화 및 노화를 예방하는데 효과가 있습니다.','resources/recipe_img/2023020222174985813.jpeg','20',20,'계피,코코넛오일,고구마',3,5,to_date('23/02/02','RR/MM/DD'),'Y');
--------------------------------------------------------
--  DDL for Index PK_RECIPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODODOG"."PK_RECIPE" ON "ODODOG"."RECIPE" ("RECIPE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RECIPE
--------------------------------------------------------

  ALTER TABLE "ODODOG"."RECIPE" ADD CONSTRAINT "PK_RECIPE" PRIMARY KEY ("RECIPE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ODODOG"."RECIPE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."RECIPE" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."RECIPE" MODIFY ("COUNT" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."RECIPE" MODIFY ("PROCESS_COUNT" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."RECIPE" MODIFY ("THUMBIMG" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."RECIPE" MODIFY ("RECIPE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."RECIPE" MODIFY ("RECIPE_TITLE" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."RECIPE" MODIFY ("RECIPE_NO" NOT NULL ENABLE);
