--------------------------------------------------------
--  파일이 생성됨 - 월요일-2월-06-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REPLY
--------------------------------------------------------

  CREATE TABLE "ODODOG"."REPLY" 
   (	"REPLY_NO" NUMBER, 
	"BOARD_TYPE" NUMBER, 
	"BOARD_NO" NUMBER, 
	"REPLY_WRITER" NUMBER, 
	"REPLY_CONTENT" VARCHAR2(1000 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ODODOG"."REPLY"."REPLY_NO" IS '댓글번호';
   COMMENT ON COLUMN "ODODOG"."REPLY"."BOARD_TYPE" IS '글분류(공지1 / 자유2/ 레시피3)';
   COMMENT ON COLUMN "ODODOG"."REPLY"."BOARD_NO" IS '참조게시글번호';
   COMMENT ON COLUMN "ODODOG"."REPLY"."REPLY_WRITER" IS '회원번호';
   COMMENT ON COLUMN "ODODOG"."REPLY"."REPLY_CONTENT" IS '댓글내용';
   COMMENT ON COLUMN "ODODOG"."REPLY"."CREATE_DATE" IS '댓글작성일';
   COMMENT ON COLUMN "ODODOG"."REPLY"."STATUS" IS '상태';
REM INSERTING into ODODOG.REPLY
SET DEFINE OFF;
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (1,3,2,3,'소 간이요?? 대박',to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (2,3,2,3,'제가 먹어봤는데 이거 맛없어요 먹지마세요',to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (3,3,4,3,'아 코코넛 싫어하는데 ',to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (4,3,2,1,'초코칩이랑 똑같이 생겼네요 짱신기하다',to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (5,3,3,1,'헐 짜장면 먹고싶다 짬뽕 레시피도 만들어주세요',to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (6,3,9,1,'사람이 먹어도 될듯',to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (8,3,4,2,'user03님 강아지가 먹는거지 님이 먹는 게 아닙니다',to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (9,3,2,2,'초코칩인줄ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (10,3,9,2,'고구마튀김 맛있겠다..,,',to_date('23/02/02','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (11,1,79,1,'넵~~',to_date('23/02/05','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (12,2,125,1,'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',to_date('23/02/05','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (13,2,120,1,'하이',to_date('23/02/05','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (14,2,124,1,'안ㄴ녕하세욥',to_date('23/02/05','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (15,1,79,2,'녱 알겠슴다',to_date('23/02/05','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (16,2,125,2,'엥..',to_date('23/02/05','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (17,1,78,3,'아ㅓㄴ녕하세요~~',to_date('23/02/05','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (18,2,124,3,'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ?',to_date('23/02/05','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (19,1,79,3,'넵 확인했습니다!',to_date('23/02/05','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (20,1,79,4,'나는 유저4',to_date('23/02/05','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (21,2,125,4,'반갑습니다요',to_date('23/02/05','RR/MM/DD'),'Y');
Insert into ODODOG.REPLY (REPLY_NO,BOARD_TYPE,BOARD_NO,REPLY_WRITER,REPLY_CONTENT,CREATE_DATE,STATUS) values (22,2,125,5,'안녕하세요 홍길동입니다',to_date('23/02/05','RR/MM/DD'),'Y');
--------------------------------------------------------
--  DDL for Index PK_REPLY
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODODOG"."PK_REPLY" ON "ODODOG"."REPLY" ("REPLY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "ODODOG"."REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY ("REPLY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ODODOG"."REPLY" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."REPLY" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."REPLY" MODIFY ("REPLY_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."REPLY" MODIFY ("REPLY_WRITER" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."REPLY" MODIFY ("BOARD_NO" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."REPLY" MODIFY ("BOARD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ODODOG"."REPLY" MODIFY ("REPLY_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "ODODOG"."REPLY" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_1" FOREIGN KEY ("REPLY_WRITER")
	  REFERENCES "ODODOG"."MEMBER" ("USER_NO") ENABLE;
